export const OPEN_START_MODAL = "OPEN_START_MODAL";
export const CLOSE_START_MODAL = "CLOSE_START_MODAL";

export const OPEN_SELECT_SERVICE_MODAL = "OPEN_SELECT_SERVICE_MODAL";
export const CLOSE_SELECT_SERVICE_MODAL = "CLOSE_SELECT_SERVICE_MODAL";
